[package]
name = "lazer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
dirs = "6.0.0"
itertools = "0.14.0"
pest = "2.7.15"
pest_derive = "2.7.15"
whoami = "1.5.2"
